package pb1interfaz.enums;

public enum MenuGestionPaciente {
	AGREGAR_PACIENTE,
	MOSTRAR_ORDENADOS_POR_COBERTURA,
	BUSCAR_POR_DNI,
	ELIMINAR_PACIENTE,
	VER_HISTORIAL_MEDICO,
	VOVLER_AL_MENU_PRINCIPAL

}
