package pb1interfaz.enums;

public enum MenuGestionTurnos {
	AGREGAR_TURNO,
	MOSTRAR_TURNOS_MAS_PROXIMOS_AL_MENOS_PROXIMO,
	BUSCAR_TURNO_POR_NOMBRE_DE_PACIENTE,
	MOSTRAR_TURNOS_DISPONIBLES_POR_ESPECIALIDAD,
	CANCELAR_TURNO,
	VOLVER_AL_MENU_PRINCIPAL

}
